## The Problem
To keep R an attractive coding language within the field of data science,
it is cental to adopt the latest advances in data manipulation. For anyone
in the R community where CPU-time and/or in-memory size is a bottleneck,
using newly available [polars](pola.rs) with optionalout-of-memory execution
can be a huge gain. Bindings for the core implementation of polars, called
rust-polars, are available for python called py-polars.

I, Søren H. Welling, have been studying polars source code and writing the
(r-polars)[https://github.com/pola-rs/r-polars] bindings full time since
March 2022. So far about 350 methods including close to all of the 'lazy'
polars expression syntax has been translated. Any known difficult integration,
e.g. calling R functions from polars threads hav been solved. However r-polars
is missing more regular method translations to become feature complete, especially
for the 'eager' syntax. Personally it strains my economy to sponsor another needed
half year on the project, which is why I humbly apply here for a scholarship.
The [r-polars](https://github.com/pola-rs/r-polars) repository has a growing interest
by the week, and new contributors make isolated PR's weekly. However for the r-polars
project to become sustainable and successful, another round of hard work is surely needed.

## Current alternatives
Already, r-arrow exists, which is likewise based on the Apache Arrow memory format.
The packages r-polars and r-arrow can co-exist well as they have near zero-copy conversion
and the same underlying types. This makes it easy to e.g. borrow a data connector from
the other package. Also r-polars can expose memory as
R [ALTREP](https://homepage.divms.uiowa.edu/~luke/talks/uiowa-2018.pdf) vectors via r-arrow +nanoarrow.
Compared to r-arrow, polars has a stronger emphasis on multi-threaded computation +
query optimization, making it the current 'king of the hill' in a
[wide set of benchmarks](https://h2oai.github.io/db-benchmark/). I predict the main polars project
will continue to improve in performance and features, as the main project has 150+ contibutors,
where of I estimate ~20 are very active.
Rspark and sparklyr likewise provide similar functionality
as polars. However, as r-polars is completely self-contained as an R package with no dependencies,
there is no need for third-party installations nor cluster configuration. This makes r-polars a
simple choice to start early development on a single desktop, with the option to later deploy the
same code in cloud 'as is' on e.g. a 64 core instance. As polars is multi-threaded instead of spark multi-noded
and have near zero-cost of memory sharing, the overhead and core efficiency of polars significantly improved.
Similar to spark, polars does not need to have the full data set in memory, as a pipeline can be streamed.
